[system]
N_sites = 1
k_max = 1.0
temp = True
tmp_dir = .

[band_structure]
band_gap = 1.4
m_e = 0.065
m_h = 2.86

[dynamics]
num_steps = 500
evolution_time = 100
dephasing_energy = 0.025

[pulse]
t0 = 10.0
sigma = 1.0
amp = 0.0001

[run_options]
shots = 2000
blocking_enable = True
blocking_qubits = 3
cuStateVec_enable = False
optimization_level = 0

[backend_options]
# device options: matrix_product_state | statevector
method = matrix_product_state
# device options: GPU | CPU
device = CPU
batched_shots_gpu = False

[noise_model]
noise = True
# model options: bitflip | frombackend
model = frombackend
