[system]
N_sites = 1
k_max = 0.39
temp = True
tmp_dir = .

[band_structure]
band_gap = 0.5
m_e = 0.065
m_h = 2.86

[dynamics]
num_steps = 500
evolution_time = 100
dephasing_energy = 0.025

[pulse]
t0 = 3.0
sigma = 0.5
amp = 0.01

[run_options]
shots = 10000
blocking_enable = False
blocking_qubits = 10
cuStateVec_enable = False
optimization_level = 2

[backend_options]
# device options: matrix_product_state | statevector
method = statevector
# device options: GPU | CPU
device = CPU
batched_shots_gpu = False

[noise_model]
noise = False
# model options: bitflip | frombackend
model = frombackend
